"""Default configuration values."""

from pathlib import Path

# Data paths
BASE_DIR = Path(__file__).resolve().parent.parent.parent
DEFAULT_DATA_DIR = BASE_DIR / "okx ob btc 2026-01-processed"

# Backtest defaults
DEFAULT_INITIAL_CAPITAL = 100000
DEFAULT_REBATE_BPS = -0.5
DEFAULT_ORDER_SIZE = 0.01
DEFAULT_MAX_SPREAD = 5.0
DEFAULT_MAX_POSITION = 1.0
DEFAULT_FILL_MODEL = "touch"
DEFAULT_SAMPLE_N = 100000

# Engine defaults
DEFAULT_VOL_WINDOW = 50
DEFAULT_SHORT_RETURN_WINDOW = 10

# AS Strategy defaults
DEFAULT_TICK_SIZE = 0.1
DEFAULT_GAMMA = 0.1
DEFAULT_BASE_SPREAD = 0.2
DEFAULT_VOL_WEIGHT = 1.0
DEFAULT_INV_WEIGHT = 1.0
DEFAULT_ALPHA_WEIGHT = 0.5
DEFAULT_IMBALANCE_WEIGHT = 0.5
DEFAULT_MIN_SPREAD = 0.1

# Robust strategy defaults
DEFAULT_MICROPRICE_WEIGHT = 1.0
DEFAULT_IMBALANCE_SIGNAL_WEIGHT = 0.3
DEFAULT_INVENTORY_WEIGHT = 2.0
DEFAULT_TARGET_SCALE = 0.3
DEFAULT_INVENTORY_SPREAD_WEIGHT = 0.2
DEFAULT_MIN_TRADE_SPREAD = 0.1
DEFAULT_EDGE_THRESHOLD = 0.03
DEFAULT_RETURN_WINDOW = 50
DEFAULT_VOL_WINDOW = 100
DEFAULT_VOL_THRESHOLD = None
DEFAULT_SIZE_SKEW = 1.5

# Output paths
DEFAULT_LOG_PATH = BASE_DIR / "maker.log"
DEFAULT_FIG_PATH = BASE_DIR / "maker_results.png"
DEFAULT_RESULTS_DIR = BASE_DIR / "results"
DEFAULT_START_DATE = "2026-01-01"
DEFAULT_END_DATE = "2026-01-31"
DEFAULT_PARAM_SAMPLES = 200
DEFAULT_TRAIN_START_DATE = "2026-01-01"
DEFAULT_TRAIN_END_DATE = "2026-01-20"
DEFAULT_TEST_START_DATE = "2026-01-21"
DEFAULT_TEST_END_DATE = "2026-01-31"
